#!/usr/bin/env zsh
local query
local fd
type -p fdfind >/dev/null 2>/dev/null && fd=fdfind || fd=fd

[[ -n ${1} && ${1} != -f ]] && {
    emacsclient -n ${1}
    return
}

[[ -n ${1} && ${1} == "-f" ]] && {
	shift
	query="-q ${@}"
}

local chosen=$(${fd} -t f|fzf -1 ${query} --preview='less {}')
[[ -n ${chosen} ]] && emacsclient -n ${chosen}
