#!/bin/zsh

if [[ $(uname -s) == "Linux" ]];then
    ETH0=$(ifconfig eth0 2>/dev/null|sed -n '/inet addr/ { s/.*inet addr://;s/ .*//;p; }')
    WLAN0=$(ifconfig wlan0|sed -n '/inet addr/ { s/.*inet addr://;s/ .*//;p; }')
elif [[ $(uname -s) == "Darwin" ]];then 
    ETH0=$(ifconfig en0 2>/dev/null|sed -n '/inet / { s/.*inet //;s/ .*//;p; }')
    WLAN0=$(ifconfig en1 2>/dev/null|sed -n '/inet / { s/.*inet //;s/ .*//;p; }')
fi

echo_it() {
    [[ -x /usr/bin/xclip ]] && echo -n $@ | xclip
    [[ -x /usr/bin/pbpaste ]] && echo -n $@ | pbpaste
    echo $@
}

if [[ -n ${ETH0} ]];then
    echo_it ${ETH0}
elif [[ -n ${WLAN0} ]];then
    echo_it ${WLAN0}
else
    return 1
fi
