#!/usr/bin/zsh

function _gh-checkmeout() {
    local query;[[ -n ${@} ]] && query="-q $@"; local c=$(env CLICOLOR_FORCE=1 gh pr list|fzf --ansi ${~query} ); [[ -n ${c} ]] && gh pr checkout $(echo $c|cut -f1)
}
_gh-checkmeout
