#!/usr/bin/env zsh
local root=${GOPATH}/src/github.com/
[[ -d ${root} ]] || root=~/
local opt_n opt_p opt fnd
local res args
local sedcmd=sed;type -p gsed >/dev/null 2>/dev/null && sedcmd=gsed # osx brew sed detection
local fdcmd=fd;type -p fdfind >/dev/null 2>/dev/null && fdcmd=fdfind # linux package

while getopts ":np" opt;do
    case $opt in
        n) opt_n=true;;
        p) opt_p=true;;
        \*) print nothing: $OPTARG; usage;;
        \?) print invalid option: $OPTARG; usage;;
    esac
done
(( OPTIND > 1 )) && shift $(( OPTIND - 1 ))

fnd=$1
type -f zshz 2> /dev/null > /dev/null || opt_n=true
if [[ -n ${fnd} ]];then

	[[ -z ${opt_n} ]] && {
		local zz=$(zshz -e ${fnd})
		[[ -n ${zz} ]] && {
			echo "ZSHZ: ${zz}"
			[[ -z ${opt_p} ]] && cd ${zz}
			return
		}
	}
	args="-q ${fnd}"
fi

res=$(${fdcmd} -d 2 -t d . ${root} | \
          ${sedcmd} -e "s,${root},,;"| \
          fzf -1 --layout=reverse-list \
              --header="Choose a directory to jump to:" \
              --min-height=10 --height 30% \
              --border ${args}
   )
[[ -n ${res} ]] && {
	echo ${root}${res}
	[[ -z ${opt_p} ]] && cd ${root}${res}
}

# vim: ft=zsh
