#!/bin/zsh


all=
[[ $1 == "-a" ]] && all="yes"

echo "Lets go do some $fg[yellow]PURGING$fg[default]"

for i in `dpkg --get-selections|grep deinstall|awk '{print $1}'`;do
	doit=

	if [[ -z $all ]];then
		echo -n "Do you want to purge $fg[cyan]$i$fg[default]: [yaN]: "
		read answer
	fi

	case $answer in
		y|Y)
			doit="yes"
			;;
		a|A)
			echo purging $fg[red]Everything$fg[default]
			all="yes"
			;;
		*)
			doit=
	esac

	[[ -n $doit || -n $all ]] && {
		echo Purging $fg[green]$i$fg[default]
		sudo dpkg --purge $i
	}
done
