#!/bin/bash
alias b='bzip2 -9vf'
alias z="gzip -9fv"
alias md='mkdir -p'

alias ls="ls --color=auto -F"
alias d=ls
alias s='cd ..'
alias p='cd -'
alias ll='ls -arSlh'
alias la='ls -A'
alias lt='ls -artl'

alias df='df -h'
alias du='du -sh'
alias cp="cp -i"
alias rm="rm -i"
alias mv="mv -i"

alias vih="$EDITOR $confdir/hosts/${HOST%%.*}.sh"
alias cdf="cd $confdir/functions/hosts/${HOST%%.*}"

(( $+commands[emacsclient] )) && alias e="emacsclient -n"

#GIT
alias ggd='git diff --ignore-space-at-eol -b -w --ignore-blank-lines'
alias gb="git checkout -b"
alias pr="git pr"
alias gc="git checkout"

function gcm() {
	git checkout $(git --no-pager branch -l --no-color|sed -rn '/.*(master|main)/ { s/^..//;p;Q;}')
	(( $+commands[gh] )) && git remote -v |grep -q github.com && gh repo sync
	git remote|grep -qw chmouel && git remote prune chmouel
    git branch --merged|sed 's/^..//'|egrep -vw '(main|master)'|xargs -r git branch -d
}
(( $+commands[gh] )) && alias ghissuecreate="gh issue create -R ${PWD:t2}"
(( $+commands[rg] )) && alias g=rg

alias fina='fin -a'
builtin type -P systemctl &>/dev/null && alias ss="sudo systemctl"
builtin type -P tailf &>/dev/null || alias tailf="tail -F"

alias grep="grep --color=auto"
