#!/bin/bash
GREP_OPTIONS="--color"
EDITOR="vim"
LESS='-F -g -i -M -R -S -w -X -z-4'

export EDITOR GREP_OPTIONS LESS

export ACK_COLOR_FILENAME="bold blue"
export ACK_COLOR_MATCH="bold red"

_ARCHI=$(uname)
export _ARCHI

type -p lessfile &>/dev/null  && eval $(lessfile)
umask 022
